-- MySQL Script generated by MySQL Workbench
-- Wed Nov 29 12:28:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema forecast
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forecast
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forecast` DEFAULT CHARACTER SET utf8 ;
USE `forecast` ;

-- -----------------------------------------------------
-- Table `forecast`.`forecast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forecast`.`forecast` (
  `id` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `localtime` DATETIME NOT NULL,
  `temp_c` DECIMAL NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `wind_mph` DECIMAL NOT NULL,
  `pressure_mb` DECIMAL NOT NULL,
  `precip_mm` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
